[package]
name = "KillLeague"
version = "0.1.1"
edition = "2024"

[dependencies]
qmetaobject = "0.2.10"
sysinfo = "0.37.2"

[profile.release]
# https://github.com/johnthagen/min-sized-rust
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"